New thump and full image
nextcloud/cookbook pull request #418
Opened 2020-11-30 11:56 UTC by TheMBeat

2020-12-01 14:32 UTC, christianlupus reviewed
Why are two different SVG files required? The idea was to have a single well-scalable image.

Additionally, it might be a good idea to popp things up with CSS+Vue changes so that the existing images are replaced by an SVG image + gray background of appropriate size.

2020-12-01 20:29 UTC, TheMBeat commented
One SVG makes more Sense. I hadn't thought through to the end.  My mistake.  I'll improve it.

2020-12-02 10:25 UTC, christianlupus commented
I will have a look later as I am quite busy currently due to day-time job.

2020-12-06 16:05 UTC, christianlupus requested changes
There is a bug in the PR. When opening the cookbook app, I get these errors in the console:
![Screenshot_20201206_170045](https://user-images.githubusercontent.com/8202922/101285370-138d5500-37e5-11eb-8abb-6b3a864e7364.png)

2020-12-06 16:05 UTC, christianlupus commented on src/components/RecipeImages.vue
> +    <div v-if="$store.state.recipe.image" :class="{ 'collapsed': collapsed , 'printable': $store.state.recipe.printImage }">
This is a white-space only change. Is this really needed?

2020-12-06 16:05 UTC, christianlupus commented on src/components/RecipeImages.vue
> +    }
What are these changes? I do not get the difference here.

2020-12-06 16:05 UTC, christianlupus commented on src/components/RecipeImages.vue
> +
White-space only can be dropped.

2020-12-06 16:12 UTC, TheMBeat commented
I look at this tomorrow.

2020-12-09 06:35 UTC, TheMBeat reviewed
@christianlupus are the changes ok for you now?

2020-12-09 17:32 UTC, christianlupus approved these changes
Looks good and I see no issues here.

2020-12-09 17:36 UTC, merged

2022-04-09 12:39 UTC, Teifun2 commented
This leads to a lot of problems in my App development.

The browser is totally happy if instead of a PNG he receives a SVG. But for normal App Components this always results in crashes deep in the library. As it gets a proper response but cannot parse the response into an image of any type.


Would it be ok if i changed the code so that the RecipeController returns 404 if no image is found. And the frontend itself adds the SVG in these cases? This seems a much cleaner "API" solution.

2022-04-10 19:27 UTC, christianlupus commented
@Teifun2 if this needs more discussion, we might be better of in a new issue instead of this PR.

Apart from that, can't you check the `Content-Type` header before?